chore: remove missing zksync stuff and text
sophon-org/dapp-portal pull request #60
Opened 2024-12-30 22:42 UTC by consvic

## Changes
- Replace missing zksync text
- Removed confusing zksync specific text and logic from codebase

2024-12-31 12:28 UTC, githubdoramon requested changes

2024-12-31 12:28 UTC, githubdoramon commented on pages/receive-methods.vue
> +          href="https://syncswap.xyz/"
https://layerswap.io/app

2024-12-31 12:28 UTC, githubdoramon commented on pages/send-methods.vue
>            target="_blank"
https://layerswap.io/app

2024-12-31 12:28 UTC, githubdoramon commented on views/transactions/Transfer.vue
> +    transferrrrrrrrrr
What is this?

2024-12-31 12:28 UTC, githubdoramon commented on views/transactions/Transfer.vue
> +            <a href="https://syncswap.xyz/" target="_blank" class="underline underline-offset-2">third-party bridges</a
https://layerswap.io/app

2025-01-01 22:10 UTC, consvic commented on views/transactions/Transfer.vue
> +    transferrrrrrrrrr
woops mb, was to test some render logic

2025-01-02 12:25 UTC, githubdoramon approved these changes

2025-01-02 12:25 UTC, merged